--- a/elyra/pipeline/kfp/processor_kfp.py
+++ b/elyra/pipeline/kfp/processor_kfp.py
@@ -213,6 +213,7 @@ class KfpPipelineProcessor(RuntimePipelineProcessor):
                     credentials=auth_info.get("credentials", None),
                     existing_token=auth_info.get("existing_token", None),
                     namespace=user_namespace,
+                    ssl_ca_cert=auth_info.get("ssl_ca_cert", None),
                 )
             else:
                 client = ArgoClient(
@@ -221,6 +222,7 @@ class KfpPipelineProcessor(RuntimePipelineProcessor):
                     credentials=auth_info.get("credentials", None),
                     existing_token=auth_info.get("existing_token", None),
                     namespace=user_namespace,
+                    ssl_ca_cert=auth_info.get("ssl_ca_cert", None),
                 )
         except Exception as ex:
             # a common cause of these errors is forgetting to include `/pipeline` or including it with an 's'
@@ -435,7 +437,7 @@ class KfpPipelineProcessor(RuntimePipelineProcessor):
 
             self.log_pipeline_info(
                 pipeline_name,
-                f"pipeline submitted: {public_api_endpoint}/#/runs/details/{run.id}",
+                f"pipeline submitted: {public_api_endpoint}/{run.id}",
                 duration=time.time() - t0,
             )
 
@@ -451,7 +453,7 @@ class KfpPipelineProcessor(RuntimePipelineProcessor):
 
         return KfpPipelineProcessorResponse(
             run_id=run.id,
-            run_url=f"{public_api_endpoint}/#/runs/details/{run.id}",
+            run_url=f"{public_api_endpoint}/{run.id}",
             object_storage_url=object_storage_url,
             object_storage_path=object_storage_path,
         )